name       : libksba
version    : 1.3.5
release    : 5
source     :
    - http://ftp.heanet.ie/mirrors/ftp.gnupg.org/gcrypt/libksba/libksba-1.3.5.tar.bz2 : 41444fd7a6ff73a79ad9728f985e71c9ba8cd3e5e53358e70d5f066d35c1a340
homepage   : http://www.gnupg.org/related_software/libksba/
license    :
    - LGPL-3.0
    - GPL-3.0
    - GPL-2.0   
summary    : Library to work with X.509 certificates
component  : security
patterns   :
    - devel:
        - /usr/bin
        - /usr/share/info
description: |
    Libksba is a library to make the tasks of working with X.509 certificates, CMS data and related objects more easy. It provides a highlevel interface to the implemented protocols and presents the data in a consistent way. There is no more need to worry about all the nasty details of the protocols. The API gives the C programmer an easy way of interacting with the data. It copes with the version details X.509 protocols tend to have as well as with the many different versions and dialects. Applications must usually cope with all of this and it has to be coded over and over again. Libksba hides this by providing just one API which does the Right Thing. Support for new features will be added as needed.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
